Add Contributing.md
salman-bhai/project-euler pull request #10
Opened 2017-10-01 03:28 UTC by ms10398

@salman-bhai Please Review

2017-10-01 04:44 UTC, sbshah97 requested changes
Make the requested changes and send it in. I'll merge it.

2017-10-01 04:44 UTC, salman-bhai commented on CONTRIBUTING.md
> +**Contributions**
Put (##) instead.

2017-10-01 04:44 UTC, salman-bhai commented on CONTRIBUTING.md
> +- A folder should be made for the seperate problem
Separate**

2017-10-01 04:46 UTC, ms10398 commented on CONTRIBUTING.md
> +- A folder should be made for the seperate problem
What is to replaced here @salman-bhai

2017-10-01 04:49 UTC, ms10398 commented on CONTRIBUTING.md
> +- A folder should be made for the seperate problem
Okay got it @salman-bhai

2017-10-01 04:57 UTC, ms10398 commented
@salman-bhai Please review

2017-10-02 03:17 UTC, ms10398 commented
https://github.com/salman-bhai/project-euler/issues/7#issuecomment-333353012 @salman-bhai review

2017-10-02 06:52 UTC, sbshah97 approved these changes
Looks good! Good work on this @ms10398 !

2017-10-02 06:52 UTC, merged

2017-10-02 09:12 UTC, ms10398 commented
Thanks @salman-bhai